Hw1 xs2421
ColumbiaOSS/project-proposals-s2023 pull request #130
Opened 2023-02-04 20:37 UTC by everssun

2023-02-05 13:29 UTC, timkpaine requested changes

2023-02-05 13:29 UTC, timkpaine commented on xs2421.md
> +Financial reinforcement learning tasks often rely on backtest results. However, backtest results often cause some overfitting issues for reasons. One step closer to real-world situation is doing [pap
move to markdown file as per instructions

2023-02-05 13:29 UTC, timkpaine commented on xs2421.md
> +Contribute to [FinRL](https://github.com/AI4Finance-Foundation/FinRL)
move to `projects/python/FinRL.md`

2023-02-05 13:29 UTC, timkpaine commented on xs2421.md
> +GitHub README: [Link](https://github.com/everssun/everssun/blob/main/README.md)
readme needs an "extra" like a badge or an embeddable app

2023-02-11 20:45 UTC, everssun commented on xs2421.md
> +GitHub README: [Link](https://github.com/everssun/everssun/blob/main/README.md)
Hi professor, I think my README page contains a "LinkedIn" badge

2023-02-14 02:42 UTC, closed without merging