HW1_pd2654 Part 2 and 3
ColumbiaOSS/project-proposals-s2023 pull request #140
Opened 2023-02-05 04:20 UTC by MirrorCraze

Add seven_wonders.md (Proposal) and numpy.md (Contributions)

Edit pd2654.md

2023-02-05 12:46 UTC, timkpaine requested changes
remove `contribution.md` and `proposal.md`

2023-02-06 04:23 UTC, MirrorCraze commented
> remove `contribution.md` and `proposal.md`

contribution.md and proposal.md is removed.

2023-02-09 20:46 UTC, timkpaine commented on pd2654.md
> +[Contribution](https://github.com/MirrorCraze/project-proposals-s2023/blob/HW1/projects/python/numpy.md)
use relative path

2023-02-14 02:43 UTC, timkpaine commented
lgtm

2023-02-14 02:43 UTC, closed without merging