HW1: Added README, updated proposal and contributions
ColumbiaOSS/project-proposals-s2023 pull request #146
Opened 2023-02-05 18:17 UTC by tchitrakorn

PR Summary:

* Added a link to README.md
* Added links to two tentative projects
* Added a link to a contribution document

2023-02-05 21:11 UTC, timkpaine requested changes

2023-02-05 21:11 UTC, timkpaine commented on README.md
> -# project-proposals-s2023
restore file

2023-02-05 21:11 UTC, timkpaine commented on mingly-issues.md
> +<h1 align="center"> ⭒❃.✮:▹ &ensp; Contributions to Mingly &ensp; ◃:✮.❃⭒ </h1>
move to `projects/javascript`

2023-02-05 21:11 UTC, timkpaine commented on lottie.md
> +<h1 align="center"> ✧༺♥༻∞ &emsp; Lottie &emsp; ∞༺♥༻✧ </h1>
move to `projects/javascript` or whatever language it is in

2023-02-05 21:11 UTC, timkpaine commented on itzma-lint.md
> +<h1 align="center"> ⭑･ﾟﾟ･*:༅｡.｡༅:*ﾟ:*:✼✿ &ensp; ITZMA Lint (It's my lint!) &ensp; ✿✼:*ﾟ:༅｡.｡༅:*･ﾟﾟ･⭑ </h1>
move to `projects/javascript` or whatever language its in

2023-02-06 04:39 UTC, tchitrakorn commented
Hi Professor @timkpaine, you have asked me to make some changes earlier. Could you please review my PR again and let me know if this is acceptable? Thank you!

2023-02-09 20:51 UTC, timkpaine requested changes

2023-02-09 20:51 UTC, timkpaine commented on tc3117.md
> +- Idea 1: [ITZMA Lint](https://github.com/tchitrakorn/project-proposals-s2023/blob/hw1/projects/python/itzma-lint.md)
use relative links like `./projects/python/itzma-lint.md` otherwise it will link to your fork of this repository instead of this repository directly

2023-02-09 20:51 UTC, timkpaine commented on tc3117.md
> +- Idea 2: [Lottie](https://github.com/tchitrakorn/project-proposals-s2023/blob/hw1/projects/python/lottie.md)
use relative link

2023-02-09 20:51 UTC, timkpaine commented on tc3117.md
> +- [Mingly](https://github.com/tchitrakorn/project-proposals-s2023/blob/hw1/projects/javascript/mingly-issues.md)
relative link

2023-02-12 05:38 UTC, tchitrakorn commented
Hi Professor @timkpaine, I've already made the changes you requested. Could you please take a look and let me know if it's alright now? Thank you!

2023-02-14 02:44 UTC, timkpaine commented
lgtm

2023-02-14 02:44 UTC, closed without merging