HW 1: Part 1, 2, and 3
ColumbiaOSS/project-proposals-s2023 pull request #161
Opened 2023-02-05 21:17 UTC by Lynanguyen0515

Update my readme link, project github repo link, wilfly-elytron description, and a link to a bug.

2023-02-05 21:32 UTC, timkpaine requested changes
Readme looks good, just need to make markdown files for your project and 1 of the projects to which you want to contribute

2023-02-05 21:32 UTC, timkpaine commented on lhn2112.md
> +Readme: [link](https://github.com/Lynanguyen0515/Lynanguyen0515)
provide direct link to file

2023-02-05 21:47 UTC, Lynanguyen0515 commented
Updated Links to .md files for my project and the project I want to contribute to.

2023-02-09 20:17 UTC, timkpaine requested changes

2023-02-09 20:17 UTC, timkpaine commented on lhn2112.md
> +Project .md File: [link](https://github.com/Lynanguyen0515/project-proposals-s2023/blob/main/pepe-pentest.md)
use relative path, like `./projects/python/pepe-pentest.md`

2023-02-09 20:17 UTC, timkpaine commented on pepe-pentest.md
> +# pepe-pentest
move to language folder like `projects/python/pepe-pentest.md`

2023-02-09 20:17 UTC, timkpaine commented on wildfly-contribute.md
> +Description of the project:
move to language folder

2023-02-13 04:45 UTC, closed without merging