HW1: Parts 1, 2 and 3
ColumbiaOSS/project-proposals-s2023 pull request #166
Opened 2023-02-05 22:00 UTC by Beza4598

2023-02-05 22:10 UTC, timkpaine requested changes

2023-02-05 22:10 UTC, timkpaine commented on baa2159.md
> +Github README: [link](https://github.com/Beza4598/Beza4598/blob/a2c5ac7ac8e7a74e59a333c29794895680303164/README.md)
use branch link not commit link:
`https://github.com/Beza4598/Beza4598/blob/main/README.md`

2023-02-05 22:10 UTC, timkpaine commented on baa2159.md
> +
add at least 1 "extra" to your README, like a badge or an embeddable app

2023-02-05 22:10 UTC, timkpaine commented on baa2159.md
> +[full project desc](https://github.com/Beza4598/project-proposals-s2023/blob/main/project_descreption.md)
use relative link like `./projects/python/<your library name>.md`

2023-02-05 22:10 UTC, timkpaine commented on baa2159.md
> +[full project desc](https://github.com/Beza4598/project-proposals-s2023/blob/main/project_contribution.md)
use relative link

2023-02-05 22:10 UTC, timkpaine commented on project_contribution.md
> +## Matplotlib
move to `projects/python/matplotlib.md`

2023-02-05 22:10 UTC, timkpaine commented on project_descreption.md
> +## Spotify to Apple Music Converter
move to `projects/python/spotify_to_apple.md` or whatever you want to call it.

2023-02-05 23:28 UTC, Beza4598 commented
Resolved all conversations

2023-02-09 19:56 UTC, timkpaine commented
lgtm

2023-02-09 19:57 UTC, closed without merging