HW 1 PR
ColumbiaOSS/project-proposals-s2023 pull request #174
Opened 2023-02-05 23:08 UTC by ayshajamjam

2023-02-07 03:25 UTC, timkpaine requested changes

2023-02-07 03:25 UTC, timkpaine commented on aj2604.md
> +- [vocab-extension](https://github.com/ayshajamjam/project-proposals-s2023/blob/main/vocab-extension.md)
Use relative link like 10am./projects/javascript/vocab-extension.md`

2023-02-07 03:25 UTC, timkpaine commented on aj2604.md
> +- [contribution](https://github.com/ayshajamjam/project-proposals-s2023/blob/main/contribution.md)
Use relative link

2023-02-07 03:25 UTC, timkpaine commented on contribution.md
> +## Project Contributions
Provide description of project according to the homework instructions, put in correct folder (like `projects/python`)

2023-02-07 03:25 UTC, timkpaine commented on vocab-extension.md
> +## Project Proposal
Move to `projects/javascript/vocab-extension.md`

2023-02-13 13:50 UTC, ayshajamjam commented
I have fixed the issues with this PR.

2023-02-14 02:37 UTC, timkpaine commented
lgtm

2023-02-14 02:37 UTC, closed without merging