HW1: Part 1 & Part 2
ColumbiaOSS/project-proposals-s2023 pull request #207
Opened 2023-02-06 03:27 UTC by ulasonat

PR for updating the ua2182.md

2023-02-06 03:30 UTC, ulasonat commented
Note that I had the PR from HW0 still open by the time of this and I closed that one to create this PR.

2023-02-07 13:25 UTC, timkpaine requested changes
Readme looks good, just need to make markdown files for your project and 1 of the projects to which you want to contribute

2023-02-07 13:25 UTC, timkpaine commented on tkp2108.md
> +GitHub: [link](https://github.com/timkpaine)
undo these changes

2023-02-12 00:33 UTC, ulasonat commented
I had two separate pull requests for HW1, which now I see was not necessary. I close this down, feel free to ignore this. My other pull request is named HW1, which I worked on branch hw1_p3!

2023-02-12 00:33 UTC, closed without merging