HW1 (hj2589)
ColumbiaOSS/project-proposals-s2023 pull request #211
Opened 2023-02-06 03:49 UTC by katehyerinjeon

2023-02-07 13:31 UTC, timkpaine requested changes

2023-02-07 13:31 UTC, timkpaine commented on contributions/pydigree.md
> +# Pydigree
move to `projects/python/pydigree.md`

2023-02-07 13:31 UTC, timkpaine commented on project/pynrm.md
> +# `pynrm`
move to `projects/python/pynrm.md`

2023-02-07 13:31 UTC, timkpaine commented on tkp2108.md
> -# Open Source Development
restore `tkp2108.md`

2023-02-08 00:34 UTC, closed without merging

2023-02-08 00:36 UTC, katehyerinjeon commented
Closed and reopened a new pull request using hw1 branch