HW1: Part 3
ColumbiaOSS/project-proposals-s2023 pull request #215
Opened 2023-02-06 04:19 UTC by ulasonat

Creating the PR for the part 3 of the HW1.

HW1 Part 1 & 2 has a different PR. Let me know if this was not the preferred way!

2023-02-07 13:37 UTC, timkpaine requested changes

2023-02-07 13:37 UTC, timkpaine commented on numpy.md
> +# Open Source Development
move to `projects/python/numpy.md`

2023-02-07 13:37 UTC, timkpaine commented on numpy.md
> +# Open Source Development
move to `projects/python/numpy.md`

2023-02-07 13:37 UTC, timkpaine commented on numpy.md
> +# Open Source Development
move to `projects/python/numpy.md`

2023-02-07 13:37 UTC, timkpaine commented on extension.md
> +# Open Source Development
move to `projects/javascript/prime-video-translate.md` or whatever you'd like to name the library

2023-02-07 13:37 UTC, timkpaine commented on tkp2108.md
> +GitHub: [link](https://github.com/timkpaine)
undo changes

2023-02-07 13:37 UTC, timkpaine commented on ua2182.md
> +
add link to project, e.g. `./projects/javascript/prime-video-translater.md`

2023-02-07 13:37 UTC, timkpaine commented on ua2182.md
> +- First issue to start with: https://github.com/numpy/numpy/issues/22536
add link to `projects/python/numpy.md`

2023-02-12 00:32 UTC, ulasonat commented
I had two pull requests for HW1, which now I see was not necessary. I closed the other pull request which was in main, this pull request (branch hw1_p3) now reflects to all part 1, part 2, and part 3 of the hw1. Let me know if you have questions!

2023-02-14 02:53 UTC, closed without merging