HW2
ColumbiaOSS/project-proposals-s2023 pull request #238
Opened 2023-02-08 03:41 UTC by cordeliachen

2023-02-09 20:25 UTC, timkpaine requested changes

2023-02-09 20:25 UTC, timkpaine commented on students/cc4655.md
> +- [spotify-charts](./projects/python/spotify-charts.md)
update link path and re-squash 😈

2023-02-09 20:25 UTC, timkpaine commented on students/cc4655.md
> +- [librosa](./projects/python/librosa.md)
update link path and re-squash 😈

2023-02-09 20:25 UTC, timkpaine requested changes

2023-02-09 20:25 UTC, timkpaine commented on projects/python/spotify-charts.md
> +
add link to your repo

2023-02-12 04:42 UTC, cordeliachen commented on students/cc4655.md
> +- [librosa](./projects/python/librosa.md)
done

2023-02-12 04:43 UTC, cordeliachen commented on projects/python/spotify-charts.md
> +
sorry, thought you meant the uni file!

2023-02-12 04:43 UTC, cordeliachen commented on students/cc4655.md
> +- [spotify-charts](./projects/python/spotify-charts.md)
done

2023-02-12 04:43 UTC, cordeliachen commented on students/cc4655.md
> +- [librosa](./projects/python/librosa.md)
done

2023-02-14 04:05 UTC, timkpaine approved these changes
lgtm

2023-02-14 04:26 UTC, merged