HW2 (ea2905) Added custoplayer and jotai project proposals
ColumbiaOSS/project-proposals-s2023 pull request #241
Opened 2023-02-08 21:24 UTC by Etesam913

✨ Added jotai.md proposal

🔗 Added links to proposals

📝 Added extra specificity on jotai proposal

🚒 Moved project into projects/javascript 📁

🔗 Changed proposal links from absolute to relative

🔗 Added repo link to custoplayer proposal

2023-02-09 20:27 UTC, timkpaine requested changes

2023-02-09 20:27 UTC, timkpaine commented on students/ea2905.md
> +![Proposal](projects/javascript/custoplayer.md)
update link path and re-squash 😈

2023-02-09 20:27 UTC, timkpaine commented on students/ea2905.md
> +![Contributions](projects/javascript/jotai.md)
update link path and re-squash 😈

2023-02-13 04:44 UTC, Etesam913 commented on students/ea2905.md
> +![Proposal](projects/javascript/custoplayer.md)
I fixed the link path

2023-02-13 04:44 UTC, Etesam913 commented on students/ea2905.md
> +![Contributions](projects/javascript/jotai.md)
I fixed the link path

2023-02-14 04:08 UTC, timkpaine approved these changes
lgtm

2023-02-14 04:26 UTC, merged