HW2: Cleanup proposals for Yash by rebasing HW1 on main
ColumbiaOSS/project-proposals-s2023 pull request #244
Opened 2023-02-09 15:24 UTC by saucam

2023-02-09 20:28 UTC, timkpaine requested changes

2023-02-09 20:28 UTC, timkpaine commented on students/yd2590.md
> +- [shiva](./projects/scala/shiva.md)
update link path and re-squash 😈

2023-02-09 20:28 UTC, timkpaine commented on students/yd2590.md
> +- [txtai](./projects/python/txtai.md)
update link paths and re-squash 😈

2023-02-10 12:44 UTC, saucam commented on students/yd2590.md
> +- [shiva](./projects/scala/shiva.md)
oops, done!

2023-02-10 12:44 UTC, saucam commented on students/yd2590.md
> +- [txtai](./projects/python/txtai.md)
done!

2023-02-10 12:45 UTC, saucam commented
@timkpaine thanks for the review, I have fixed the links so should be good. Maybe can take another look?

2023-02-11 18:05 UTC, merged