HW2: Rebased onto main branch
ColumbiaOSS/project-proposals-s2023 pull request #253
Opened 2023-02-09 22:55 UTC by cherieliu

Added personal README to proposal file, created project files, and added the project repo link to the file

2023-02-10 21:01 UTC, timkpaine requested changes

2023-02-10 21:01 UTC, timkpaine commented on students/cl3945.md
> +- [color-template](./projects/javascript/color-template.md)
update link path and re-squash 😈

2023-02-10 21:01 UTC, timkpaine commented on students/cl3945.md
> +- [Material UI](./projects/javascript/material-ui.md)
update link path and re-squash 😈

2023-02-11 14:11 UTC, cherieliu commented on students/cl3945.md
> +- [color-template](./projects/javascript/color-template.md)
Fixed in new commit!

2023-02-11 14:11 UTC, cherieliu commented on students/cl3945.md
> +- [Material UI](./projects/javascript/material-ui.md)
Fixed in new commit!

2023-02-11 18:09 UTC, merged