HW2
ColumbiaOSS/project-proposals-s2023 pull request #277
Opened 2023-02-11 19:18 UTC by asharnadeem

2023-02-11 20:33 UTC, timkpaine requested changes

2023-02-11 20:33 UTC, timkpaine commented on students/an3056.md
> +- [tool-kit](https://github.com/asharnadeem/tool-kit)
relative path to markdown file

2023-02-11 20:33 UTC, timkpaine commented on students/an3056.md
> +- [faker](./projects/python/faker.md)
update link path and re-squash 😈

2023-02-11 23:39 UTC, asharnadeem commented on students/an3056.md
> +- [faker](./projects/python/faker.md)
Addressed

2023-02-11 23:39 UTC, asharnadeem commented on students/an3056.md
> +- [tool-kit](https://github.com/asharnadeem/tool-kit)
Addressed

2023-02-14 04:01 UTC, timkpaine commented
lgtm

2023-02-14 04:02 UTC, timkpaine approved these changes

2023-02-14 04:25 UTC, merged