HW2
ColumbiaOSS/project-proposals-s2023 pull request #285
Opened 2023-02-11 21:55 UTC by mwsepulveda

Finished HW1 by adding project and contribution descriptions in md files. Updated proposal md file accordingly.

Finished HW2 by adding link to new project repo in noobJS.md.

2023-02-11 22:08 UTC, mwsepulveda commented
Realized that I should change the file paths within the students/mws2170.md file since the paths there were from the mws2170.md file in my repo home directory (I believe this was the instruction from hw0, to place it on its own outside of the students directory). Will points be taken off for this for HW2, or could I fix this later?

2023-02-11 22:28 UTC, timkpaine requested changes

2023-02-11 22:28 UTC, timkpaine commented on mws2170.md
> +- [noobJS](./projects/javascript/noobJS.md)
update link path and re-squash

2023-02-11 22:28 UTC, timkpaine commented on mws2170.md
> +- [freeCodeCamp](./projects/javascript/freecodecamp.md)
update link path and re-squash

2023-02-14 04:14 UTC, timkpaine requested changes

2023-02-14 04:14 UTC, timkpaine commented on mws2170.md
> +# Open Source Development
remove file, in `students/` now

2023-02-19 23:14 UTC, merged