mjk2244 HW0
ColumbiaOSS/project-proposals-s2023 pull request #30
Opened 2023-01-23 20:05 UTC by mjk2244

Matt Kim mjk2244 HW 0 - project proposals and contributions

2023-01-25 20:24 UTC, mjk2244 commented
Original PR had broken hyperlinks

2023-01-31 19:50 UTC, mjk2244 commented
link to my profile README.md now included in mjk2244.md

2023-02-01 17:54 UTC, timkpaine requested changes

2023-02-01 17:54 UTC, timkpaine commented on mjk2244.md
> +GitHub README: [link](https://github.com/timkpaine/timkpaine/blob/main/README.md](https://github.com/mjk2244/mjk2244/blob/main/README.md))
`[link](https://github.com/timkpaine/timkpaine/blob/main/README.md](https://github.com/mjk2244/mjk2244/blob/main/README.md))`

malformed, and should be in separate PR for HW1

2023-02-04 22:51 UTC, merged