HW2-jp4013
ColumbiaOSS/project-proposals-s2023 pull request #361
Opened 2023-02-13 06:18 UTC by jaesungpark42

I cannot find why it won't automatically merge yet can still let me rebase yet.

2023-02-14 03:45 UTC, timkpaine requested changes
ensure all commits squashed into 1

2023-02-14 03:45 UTC, timkpaine commented on projects/python/chatGPTCoverLetterGenerator.md
> +New Project Idea:
include link to project repo

2023-02-14 03:45 UTC, timkpaine commented on jp4013.md
this file should've ended up in `students/`

2023-02-14 03:45 UTC, timkpaine commented on jp4013.md
> +[chatGPTCoverLetterGenerator](./projects/python/chatGPTCoverLetterGenerator.md)
update path after moving to `students`, e.g. `../projects/...`

2023-02-14 03:45 UTC, timkpaine commented on jp4013.md
> +[jobAppAutofiller](./projects/javascript/jobAppAutofiller.md)
update path

2023-02-17 04:21 UTC, jaesungpark42 commented
It let me squash the changes on rebase but it doesn't show up here. I'm confused.

2023-02-19 23:59 UTC, closed without merging