HW2 - afs2185
ColumbiaOSS/project-proposals-s2023 pull request #362
Opened 2023-02-13 07:03 UTC by afsong

add multithreading library description

Add serenity description

Add link to markdown files

fix path

add hw2 link

2023-02-14 03:46 UTC, timkpaine requested changes

2023-02-14 03:46 UTC, timkpaine commented on students/afs2185.md
> +[MTLibrary](./projects/cpp/multithreading.md)
update link path and re-squash 😈

2023-02-14 03:46 UTC, timkpaine commented on students/afs2185.md
> +[SerenityOS](./projects/cpp/SerenityOS.md)
update link path and re-squash 😈

2023-02-14 03:46 UTC, timkpaine commented on projects/cpp/multithreading.md
> +# Multithreading Library in C++
add project link here

2023-02-16 07:06 UTC, afsong commented on projects/cpp/multithreading.md
> +# Multithreading Library in C++
added in the correct file

2023-02-16 07:06 UTC, afsong commented on students/afs2185.md
> +[SerenityOS](./projects/cpp/SerenityOS.md)
link path updated

2023-02-16 07:06 UTC, afsong commented on students/afs2185.md
> +[MTLibrary](./projects/cpp/multithreading.md)
link path updated

2023-02-19 23:25 UTC, merged