HW2: Squashed and rebased commits
ColumbiaOSS/project-proposals-s2023 pull request #374
Opened 2023-02-14 21:48 UTC by cgr2134

Create nikefy.md

Create pandas.md

Update cgr2134.md

Update nikefy.md

2023-02-16 19:32 UTC, timkpaine requested changes

2023-02-16 19:32 UTC, timkpaine commented on students/cgr2134.md
> +* [nikefy](./projects/python/nikefy.md)
update path to `../` and re squash

2023-02-16 19:32 UTC, timkpaine commented on students/cgr2134.md
> +* [pandas](./projects/python/pandas.md)
update path to `../` and re squash

2023-02-19 00:29 UTC, cgr2134 commented
updated path to ../

2023-02-19 23:32 UTC, timkpaine requested changes

2023-02-19 23:32 UTC, timkpaine commented on students/cgr2134.md
> +* [nikefy](../projects/python/nikefy.md)
this file doesn't seem to exist

2023-02-20 01:08 UTC, cgr2134 commented on students/cgr2134.md
> +* [nikefy](../projects/python/nikefy.md)
created nikefy.md file should work now

2023-02-20 01:32 UTC, merged