Homework2
ColumbiaOSS/project-proposals-s2023 pull request #390
Opened 2023-02-19 02:08 UTC by ayshajamjam

2023-02-19 23:27 UTC, timkpaine requested changes
ensure commits are squashed into 1

2023-02-19 23:27 UTC, timkpaine commented on students/aj2604.md
> +- [vocab-extension](./projects/javascript/vocab-extension.md)
update path to `../`

2023-02-19 23:27 UTC, timkpaine commented on students/aj2604.md
> +- [contribution](./projects/python/contribution.md)
update path to `../`

2023-02-21 22:19 UTC, ayshajamjam commented on students/aj2604.md
> +- [vocab-extension](./projects/javascript/vocab-extension.md)
Done

2023-02-21 22:20 UTC, ayshajamjam commented on students/aj2604.md
> +- [contribution](./projects/python/contribution.md)
Done

2023-02-23 20:25 UTC, merged