HW2 (mw3071) rebased to fix conflicts
ColumbiaOSS/project-proposals-s2023 pull request #404
Opened 2023-02-22 23:45 UTC by mw3071

Added Github readme and profile link

Create columbia-discord-bot.md

Create discord-py.md

moved to projects/python folder

Delete discord-py.md since already exists in /python

Create discordpy.md

2023-02-23 20:54 UTC, timkpaine requested changes

2023-02-23 20:54 UTC, timkpaine commented on mw3071.md
> +<h1>Open Source Development</h1>
move file to `students/mw3071.md`, use markdown format for whole file

2023-02-23 20:54 UTC, timkpaine commented on mw3071.md
> +Columbia Discord Bot
markdown link to file

2023-02-23 20:54 UTC, timkpaine commented on mw3071.md
> +Discordpy
markdown link to file

2023-02-23 20:54 UTC, timkpaine commented on projects/python/columbia-discord-bot.md
> +projects/columbia-discord-bot.md
remove this line

2023-02-23 20:54 UTC, timkpaine commented on projects/python/columbia-discord-bot.md
> +
link to project repository

2023-02-23 20:54 UTC, timkpaine commented on projects/python/discordpy.md
> +projects/discordpy.md
remove this line

2023-03-23 00:04 UTC, mw3071 commented
created pull request for the file in students/mw3071.md:
https://github.com/ColumbiaOSS/project-proposals-s2023/pull/431

2023-04-20 17:54 UTC, merged